export const SWITCH_LOADER = 'SWITCH_LOADER';
export const SHOW_SELECTED = "SHOW_SELECTED";
export const SET_SETTINGS = "SET_SETTINGS";
export const SET_VIEWPORT ="SET_VIEWPORT";
export const CHECK_USER_LOGIN = "CHECK_USER_LOGIN";
export const ADD_PRODUCT_TO_COLLECTION = "ADD_PRODUCT_TO_COLLECTION";
export const ADD_COLLECTION_TO_FAVORUITE = "ADD_COLLECTION_TO_FAVORUITE";
